/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Dokter1 extends javax.swing.JFrame {

    /**
     * Creates new form Dokter1
     */
    Date today = new Date();
    private  DefaultTableModel model;
    private String file;
    public Dokter1() {
        initComponents();
        autokode();
        setTitle("Riez Hadiningrat");
        ldate.setText(today.toString());
        
          
         model = new DefaultTableModel();
        tbldokter.setModel(model);
        model.addColumn("id_dokter");
        model.addColumn("nama");
        model.addColumn("jenis_kelamin");
        model.addColumn("spesialist");
        model.addColumn("umur");
        model.addColumn("Foto");

        loadData();
        
        
    }
       private void clear() {
        iddokter.setText("");
        namadok.setText("");
        spesialis.setSelectedIndex(0);
        txtjenis.setSelectedIndex(0);
        txtumur.setText("");
        gambar.setText("");
        tampil_gambar.setText("");


    }
     

public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = koneksi.getkoneksi();
            try (Statement s = c.createStatement()) {
                String sql = "Select * from dokter";
            try (ResultSet r = s.executeQuery(sql)) {
                    while (r.next()) {
                        Object[] o = new Object[6];
                        o[0] = r.getString("id_dokter");
                        o[1] = r.getString("nama");
                        o[2] = r.getString("jenis_kelamin");
                        o[3] = r.getString("spesialist");
                        o[4] = r.getString("umur");
                        o[5] = r.getString("foto");
                        model.addRow(o);
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println("tdk Bisa Load");
        }
}
            
        private void search(String sql){
            
        model = new DefaultTableModel();
        tbldokter.setModel(model);
        model.addColumn("id_dokter");
        model.addColumn("nama");
        model.addColumn("jenis_kelamin");
        model.addColumn("spesialist");
        model.addColumn("umur");
        model.addColumn("foto");
       
        
        //String cari = txtcari.getText();
            try {
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
          
            ResultSet rs = s.executeQuery(sql);
        if (rs.next()){
            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
        }
        else {
            JOptionPane.showMessageDialog(this,"DATA TIDAK ADA","ALERT",JOptionPane.ERROR_MESSAGE);
            
        }
         tbldokter.setModel(model);
        }catch(SQLException e){
        
        }

}
        private void autokode(){
    try{ Connection c=koneksi.getkoneksi();
     Statement s=c.createStatement();
     String sql= "SELECT MAX(right(id_dokter,4)) AS id_dokter FROM dokter";
     ResultSet rs = s.executeQuery(sql);
        while(rs.next()){
                if(rs.first() == false){
                iddokter.setText("0001");
        }
                else {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<4-noLong;a++){
                        no = "0" + no;
         }
                   iddokter.setText(1+no);
               }       
            }
       rs.close();
       s.close(); }   
catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR: \n" + e.toString(),
                            "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asd = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tgl2 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        tgl3 = new javax.swing.JLabel();
        tgl1 = new javax.swing.JLabel();
        spesialis = new javax.swing.JComboBox();
        namadok = new javax.swing.JTextField();
        iddokter = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldokter = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ldate = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtjenis = new javax.swing.JComboBox();
        txtumur = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gambar = new javax.swing.JTextField();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton4 = new javax.swing.JButton();
        tampil_gambar = new javax.swing.JLabel();

        asd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        asd.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nama Dokter");

        jLabel5.setText("Spesialist");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Umur");

        jLabel3.setText("ID Dokter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 270));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Daftar Dokter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        tgl2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tgl.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tgl3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(tgl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tgl1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        spesialis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "penyakit-dalam", "THT", "jantung", "kebidanan", "mata", "kulit&kelamin" }));
        getContentPane().add(spesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 180, 29));

        namadok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namadokActionPerformed(evt);
            }
        });
        getContentPane().add(namadok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));

        iddokter.setEnabled(false);
        iddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddokterActionPerformed(evt);
            }
        });
        getContentPane().add(iddokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 80, 25));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, -1));

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, -1));

        tbldokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbldokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldokterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldokter);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 910, 250));

        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        ldate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(ldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 203, 27));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 30));

        jButton2.setText("CARI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 80, 30));

        txtjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "laki-laki", "perempuan" }));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 29));

        txtumur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtumurActionPerformed(evt);
            }
        });
        getContentPane().add(txtumur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, 29));

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 80, -1));

        jLabel2.setText("Foto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        gambar.setEnabled(false);
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 170, 20));
        getContentPane().add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 10, 10));

        jButton4.setText("CARI");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 60, -1));

        tampil_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tampil_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 310, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namadokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namadokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namadokActionPerformed

    private void iddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddokterActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Yakin Hapus BOK ??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
        int i=tbldokter.getSelectedRow();
        if(1==-1)
        {
            return;
        }

        String id=(String) model.getValueAt(i, 0);

        try {
            Connection c=koneksi.getkoneksi();
            String sql = "DELETE From dokter WHERE id_dokter=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, id);

            p.executeUpdate();
            p.close();

        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());;
        }finally{
            loadData();
            clear();
            autokode();
            tampil_gambar.setText("");
        }
    }//GEN-LAST:event_deleteActionPerformed
    }
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String jenis = spesialis.getSelectedItem().toString();
        String spesial = txtjenis.getSelectedItem().toString();

        String id_dokter = iddokter.getText();
        String nama = namadok.getText();
        String umur = txtumur.getText();
       String foto = gambar.getText();
        
int ok = JOptionPane.showConfirmDialog(null, "Yakin BOK ??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
        try {
            Connection c = koneksi.getkoneksi();
            String sql = "Insert Into dokter Values (?,?,?,?,?,?)";

            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
            p.setString(1, id_dokter);
            p.setString(2, nama);
            p.setString(3, spesial);
            p.setString(4, jenis);
            p.setString(5, umur);
            p.setString(6, foto); 
            

            p.executeUpdate();
            p.close();

        } catch (SQLException e) {
            System.out.println("Tidak Bisa Isi");
        } finally {
            loadData();
            

            if (iddokter.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Periksa Kembali");
            } else {

                clear();
                autokode();

            }

        }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tbldokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldokterMouseClicked
        // TODO add your handling code here:
        int i = tbldokter.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id=(String) model.getValueAt(i, 0);
        iddokter.setText(id);
        String nama = (String) model.getValueAt(i, 1);
        namadok.setText(nama);       
        String jenis = (String) model.getValueAt(i, 2);
        txtjenis.setSelectedItem(jenis);
        String speisal = (String) model.getValueAt(i, 3);
        spesialis.setSelectedItem(speisal);
        String umur = (String) model.getValueAt(i, 4);
        txtumur.setText(umur);
        String icon = (String) model.getValueAt(i, 5);
        gambar.setText(icon);
       
        ImageIcon gambar1 = new ImageIcon(gambar.getText()); // jangan lupa import class ImageIcon
        tampil_gambar.setIcon(gambar1);
       
    }//GEN-LAST:event_tbldokterMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cari = txtcari.getText();
        String sql= "select * from dokter where nama like'"+cari+"%'";        
        search(sql);
        txtcari.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtumurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtumurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtumurActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            if (iddokter.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Nomor Tidak Boleh KOSONG BOK", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
               Connection c = koneksi.getkoneksi();
                Statement s=c.createStatement();
              
                String sql ="update dokter set nama='" + namadok.getText() + "',jenis_kelamin='" + txtjenis.getSelectedItem() + "',spesialist='" + spesialis.getSelectedItem() + "',umur='" + txtumur.getText()+"',foto='"+gambar.getText()+"' where id_dokter='" + iddokter.getText() + "'";
                 boolean r=s.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Update Tersimpan !", "Update", JOptionPane.INFORMATION_MESSAGE);
                clear();
                loadData();
                autokode();
                tampil_gambar.setText("");
            }
            loadData();
            
        }catch(SQLException error_update){
            JOptionPane.showMessageDialog(rootPane, "Error : "+error_update.getMessage(), "Update Gagal", JOptionPane.ERROR_MESSAGE);
            clear();
            autokode();
            tampil_gambar.setText("");
        }
                                           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:

       jFileChooser1.setSelectedFile(null);
        jFileChooser1.showOpenDialog(this);
        file = jFileChooser1.getSelectedFile().toString();

        file = file.replace('\\', '/');
        gambar.setText(file);

        ImageIcon icon = new ImageIcon(file); // jangan lupa import class ImageIcon
        tampil_gambar.setIcon(icon);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home(Login1.kondisiLogin).show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asd;
    private javax.swing.JButton delete;
    private javax.swing.JTextField gambar;
    private javax.swing.JTextField iddokter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ldate;
    private javax.swing.JTextField namadok;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox spesialis;
    private javax.swing.JLabel tampil_gambar;
    private javax.swing.JTable tbldokter;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel tgl1;
    private javax.swing.JLabel tgl2;
    private javax.swing.JLabel tgl3;
    private javax.swing.JTextField txtcari;
    private javax.swing.JComboBox txtjenis;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
}
