/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author root
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    int kodelogin;
    public Home(int login) {
        initComponents();
    
        setTitle("Riez Hadiningrat");
        kodelogin = login; 
        belumLogin();
        
        if (login == 0) {
            LoginAdmin();
        }else if (login == 1){
            LoginUser();
        }else{
            belumLogin();
        }
        
    }
            
private void belumLogin() { 
txtjud.setVisible(false);
txtobat.setVisible(false);
txtdokter.setVisible(false);

txtkasir.setVisible(false);
txttrans.setVisible(false);

txtpeng.setVisible(false);


tulis1.setVisible(false);
tulis2.setVisible(false);

tulis4.setVisible(false);
tulis5.setVisible(false);

tulis7.setVisible(false);
tulis8.setVisible(false);



}

private void LoginAdmin() {
txtjud.setVisible(true);
txtobat.setVisible(true);
txtdokter.setVisible(true);

txtkasir.setVisible(true);
txttrans.setVisible(true);
tulis1.setVisible(true);
tulis2.setVisible(true);

tulis4.setVisible(true);
tulis5.setVisible(true);

tulis7.setVisible(true);
tulis8.setVisible(true);

txtpeng.setVisible(true);

}

private void LoginUser() {
txtjud.setVisible(true);
txtobat.setVisible(true);
txtdokter.setVisible(false);

txtkasir.setVisible(false);
txttrans.setVisible(true);
tulis1.setVisible(true);
tulis2.setVisible(true);

tulis4.setVisible(true);
tulis5.setVisible(false);

tulis7.setVisible(false);
tulis8.setVisible(false);



    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtjud = new javax.swing.JLabel();
        txtdokter = new javax.swing.JLabel();
        txtobat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkasir = new javax.swing.JLabel();
        txttrans = new javax.swing.JLabel();
        tulis1 = new javax.swing.JLabel();
        tulis2 = new javax.swing.JLabel();
        tulis4 = new javax.swing.JLabel();
        tulis5 = new javax.swing.JLabel();
        txtpeng = new javax.swing.JLabel();
        tulis7 = new javax.swing.JLabel();
        tulis8 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("Pembayaran");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtjud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/jud.png"))); // NOI18N
        txtjud.setToolTipText("REKAMEDIS");
        txtjud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtjudMouseClicked(evt);
            }
        });
        getContentPane().add(txtjud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 120));

        txtdokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/dokter.png"))); // NOI18N
        txtdokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdokterMouseClicked(evt);
            }
        });
        getContentPane().add(txtdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 130, 130));

        txtobat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/obat.png"))); // NOI18N
        txtobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtobatMouseClicked(evt);
            }
        });
        getContentPane().add(txtobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/1425081779_logout-48.png"))); // NOI18N
        jLabel1.setToolTipText("LOGOUT");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/banner.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 140));

        txtkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/1425588138_Add-Male-User.png"))); // NOI18N
        txtkasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtkasirMouseClicked(evt);
            }
        });
        getContentPane().add(txtkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 130, 130));

        txttrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/1425604391_cash_register.png"))); // NOI18N
        txttrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttransMouseClicked(evt);
            }
        });
        getContentPane().add(txttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 140, 120));

        tulis1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tulis1.setText("Rekamedis");
        getContentPane().add(tulis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 90, -1));

        tulis2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tulis2.setText("Obat");
        getContentPane().add(tulis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 40, -1));

        tulis4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tulis4.setText("Pembayaran");
        getContentPane().add(tulis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 100, -1));

        tulis5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tulis5.setText("Dokter");
        getContentPane().add(tulis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 60, 20));

        txtpeng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/1426819282_Salary-128.png"))); // NOI18N
        txtpeng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpengMouseClicked(evt);
            }
        });
        getContentPane().add(txtpeng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 100));

        tulis7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tulis7.setText("User ");
        getContentPane().add(tulis7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        tulis8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tulis8.setText("Penggajian");
        getContentPane().add(tulis8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtjudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjudMouseClicked
        // TODO add your handling code here:
        new Rekamedis().show();
        this.dispose();
    }//GEN-LAST:event_txtjudMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Login1().show();
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtdokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdokterMouseClicked
        // TODO add your handling code here:
        new Dokter1().show();
        this.dispose();
    }//GEN-LAST:event_txtdokterMouseClicked

    private void txtkasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtkasirMouseClicked
        // TODO add your handling code here
        new Kasir().show();
        this.dispose();
    }//GEN-LAST:event_txtkasirMouseClicked

    private void txtobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtobatMouseClicked
        // TODO add your handling code here:
        new obat().show();
        this.dispose();
    }//GEN-LAST:event_txtobatMouseClicked

    private void txttransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttransMouseClicked
        // TODO add your handling code here:
        new laborat().show();
        this.dispose();
    }//GEN-LAST:event_txttransMouseClicked

    private void txtpengMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpengMouseClicked
        // TODO add your handling code here:
        new Penggajian().show();
        this.dispose();
    }//GEN-LAST:event_txtpengMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(Login1.kondisiLogin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tulis1;
    private javax.swing.JLabel tulis2;
    private javax.swing.JLabel tulis4;
    private javax.swing.JLabel tulis5;
    private javax.swing.JLabel tulis7;
    private javax.swing.JLabel tulis8;
    private javax.swing.JLabel txtdokter;
    private javax.swing.JLabel txtjud;
    private javax.swing.JLabel txtkasir;
    private javax.swing.JLabel txtobat;
    private javax.swing.JLabel txtpeng;
    private javax.swing.JLabel txttrans;
    // End of variables declaration//GEN-END:variables
}
