/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author angcmd
 */


public class laborat extends javax.swing.JFrame {
    koneksi koneksi;
    String tanggal1;
    /**
     * Creates new form laborat
     */
    Date today = new Date();
    public laborat() {
        initComponents();
        autokode();
        tampilcombo();
        txttampil.setVisible(false);
        setTitle("Riez Hadiningrat");
        
        ldate.setText(today.toString());
    }
    private void clear() {
        txtkd.setText("");
        txtnorekam.setText("");
        
        txtnama.setText("");
        txtumur.setText("");
        txtalamat.setText("");
        txtjamin.setText("");
        txtiddok.setText("");
        txtnamadok.setText("");
        txtspesial.setText("");
        txtjenis.setSelectedIndex(0);
        cmbobat1.setSelectedIndex(0);
        cmbobat2.setSelectedIndex(0);
        cmbobat3.setSelectedIndex(0);
        cmbobat4.setSelectedIndex(0);
        cmbobat5.setSelectedIndex(0);
        cmbobat6.setSelectedIndex(0);
        cmbobat7.setSelectedIndex(0);
        hgobat1.setText("");
        hgobat2.setText("");
        hgobat3.setText("");
        hgobat4.setText("");
        hgobat5.setText("");
        hgobat6.setText("");
        hgobat7.setText("");
        total1.setText("");
        total2.setText("");
        total3.setText("");
        total4.setText("");
        total5.setText("");
       total6.setText("");
        total7.setText("");
        tampil_gambar.setText("Foto");
    }
    private void autokode(){
    try{ Connection c=koneksi.getkoneksi();
     Statement s=c.createStatement();
     String sql= "SELECT MAX(right(no_transaksi,4)) AS no_transaksi FROM transaksi";
     ResultSet rs = s.executeQuery(sql);
        while(rs.next()){
                if(rs.first() == false){
                txtkd.setText("0001");
        }
                else {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<4-noLong;a++){
                        no = "0"+ no;
         }
                   txtkd.setText(1+no);
               }       
            }
       rs.close();
       s.close(); }   
catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR: \n" + e.toString(),
                            "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        btnlaporan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cmbobat1 = new javax.swing.JComboBox();
        total1 = new javax.swing.JTextField();
        cmbobat2 = new javax.swing.JComboBox();
        total2 = new javax.swing.JTextField();
        cmbobat3 = new javax.swing.JComboBox();
        total3 = new javax.swing.JTextField();
        cmbobat4 = new javax.swing.JComboBox();
        cmbobat5 = new javax.swing.JComboBox();
        cmbobat6 = new javax.swing.JComboBox();
        cmbobat7 = new javax.swing.JComboBox();
        total4 = new javax.swing.JTextField();
        total5 = new javax.swing.JTextField();
        total6 = new javax.swing.JTextField();
        total7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        hgobat1 = new javax.swing.JLabel();
        hgobat2 = new javax.swing.JLabel();
        hgobat3 = new javax.swing.JLabel();
        hgobat4 = new javax.swing.JLabel();
        hgobat5 = new javax.swing.JLabel();
        hgobat6 = new javax.swing.JLabel();
        hgobat7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ldate = new javax.swing.JLabel();
        txtjenis = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtnorekam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtumur = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtiddok = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtnamadok = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtspesial = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtjamin = new javax.swing.JTextField();
        tampil_gambar = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txttampil = new javax.swing.JLabel();

        jLabel28.setText("jLabel28");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kode Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Jenis Pemeriksaan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        txtkd.setEnabled(false);
        getContentPane().add(txtkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        btnlaporan.setText("SIMPAN");
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        btnkeluar.setText("KEMBALI");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbobat1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 116, -1));

        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });
        jPanel1.add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 11, 35, -1));

        cmbobat2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 116, -1));

        total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total2ActionPerformed(evt);
            }
        });
        jPanel1.add(total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 37, 35, -1));

        cmbobat3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, 116, -1));

        total3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total3ActionPerformed(evt);
            }
        });
        jPanel1.add(total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 63, 35, -1));

        cmbobat4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat4ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 116, -1));

        cmbobat5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat5ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 116, -1));

        cmbobat6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat6ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, 116, -1));

        cmbobat7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----" }));
        cmbobat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobat7ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbobat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, 116, -1));

        total4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total4ActionPerformed(evt);
            }
        });
        jPanel1.add(total4, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 89, 35, -1));

        total5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total5ActionPerformed(evt);
            }
        });
        jPanel1.add(total5, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 115, 35, -1));

        total6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total6ActionPerformed(evt);
            }
        });
        jPanel1.add(total6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 141, 35, -1));

        total7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total7ActionPerformed(evt);
            }
        });
        jPanel1.add(total7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 167, 35, -1));

        jLabel7.setText("x");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 14, -1, -1));

        jLabel8.setText("x");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 37, -1, -1));

        jLabel9.setText("x");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 66, -1, -1));

        jLabel10.setText("x");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 92, -1, -1));

        jLabel11.setText("x");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 118, -1, -1));

        jLabel12.setText("x");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 144, -1, -1));

        jLabel13.setText("x");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 170, -1, -1));

        jLabel15.setText("@");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 14, -1, -1));

        jLabel16.setText("@");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel17.setText("@");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 66, -1, -1));

        jLabel18.setText("@");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 92, -1, -1));

        jLabel19.setText("@");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 118, -1, -1));

        jLabel20.setText("@");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 144, -1, -1));

        jLabel21.setText("@");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));
        jPanel1.add(hgobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 20));
        jPanel1.add(hgobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 40, 60, 20));
        jPanel1.add(hgobat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 66, 60, 20));
        jPanel1.add(hgobat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 92, 60, 20));
        jPanel1.add(hgobat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 144, 60, 20));
        jPanel1.add(hgobat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 118, 60, 20));
        jPanel1.add(hgobat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 170, 50, 20));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, 260));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Total");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 100, -1));

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 140, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        ldate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(ldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 10, 340, 27));

        txtjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Gula Darah", "Asam Urat", "Ejakulasi Dini", "Kolesterol" }));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 190, -1));

        jLabel4.setText("No Rekamedis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtnorekam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnorekamActionPerformed(evt);
            }
        });
        getContentPane().add(txtnorekam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, -1));

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtnama.setEnabled(false);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, -1));

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtalamat.setEnabled(false);
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 50));

        jLabel22.setText("Umur");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtumur.setEnabled(false);
        getContentPane().add(txtumur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 40, -1));

        jLabel23.setText("Tahun");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jLabel24.setText("ID Dokter");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        txtiddok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddokActionPerformed(evt);
            }
        });
        getContentPane().add(txtiddok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, -1));

        jLabel25.setText("Obat");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        jLabel26.setText("Nama Dokter");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        txtnamadok.setEnabled(false);
        getContentPane().add(txtnamadok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 190, -1));

        jLabel27.setText("Spesialist");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        txtspesial.setEnabled(false);
        getContentPane().add(txtspesial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 110, -1));

        jLabel29.setText("Jaminan");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtjamin.setEnabled(false);
        getContentPane().add(txtjamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 110, -1));

        tampil_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tampil_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 310, 400));
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));
        getContentPane().add(txttampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//method tampil combo
public void tampilcombo(){
try {
Connection c=koneksi.getkoneksi();
        Statement s=c.createStatement();
        String sql="Select * from obat";
        ResultSet r=s.executeQuery(sql);
        while(r.next()){
            cmbobat1.addItem(r.getString(2));
            cmbobat2.addItem(r.getString(2));
            cmbobat3.addItem(r.getString(2));
            cmbobat4.addItem(r.getString(2));
            cmbobat5.addItem(r.getString(2));
            cmbobat6.addItem(r.getString(2));
            cmbobat7.addItem(r.getString(2));
        }
        r.close();
        s.close();
        
    }catch(SQLException e){
        System.out.println("tdk bisa Load");
        
    }



}
public void tampiluser(){
try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from rekamedis where no_rekamedis='"+txtnorekam.getText()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
            
            txtnama.setText(rs.getString(2));
            txtalamat.setText(rs.getString(3));
            txtumur.setText(rs.getString(5));
            txtjamin.setText(rs.getString(6));
            
            }
     else{
         JOptionPane.showMessageDialog(null, "Tak ada");
     }
} catch (Exception e){
        JOptionPane.showMessageDialog(null, "Tak ada");
}
        
    }
    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        // TODO add your handling code here:
     
        
 int ok = JOptionPane.showConfirmDialog(null, "Yakin BOK??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
           
        String no_transaksi = txtkd.getText();
        String no_rekamedis = txtnorekam.getText();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String umur = txtumur.getText();
        String jaminan = txtjamin.getText();
        String id_dokter =txtiddok.getText();
        String nm_dokter =txtnamadok.getText();
        String spesialist = txtspesial.getText();
        String jenis = txtjenis.getSelectedItem().toString();
        String tanggal = ldate.getText();
        String total = txttotal.getText();

        try {
            Connection c = koneksi.getkoneksi();
            String sql = "insert into transaksi values (?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
            p.setString(1, no_transaksi);
            p.setString(2, no_rekamedis);
            p.setString(3, nama);
            p.setString(4, alamat);
            p.setString(5, umur);
            p.setString(6, jaminan);
            p.setString(7, id_dokter);
            p.setString(8, nm_dokter);
            p.setString(9, spesialist);
            p.setString(10, jenis);
            p.setString(11, tanggal);
            p.setString(12, total);
            
            p.executeUpdate();
            p.close();

           
        } catch (SQLException e) {
            System.out.println("Tidak Bisa Isi");
        } finally {
            

            if (txtnorekam.getText().isEmpty()) ;  if (txtiddok.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cek Maning BOK !");
                 
                 
            } else {
       
        clear();
       autokode();

            }
            
            
        }
            }


        
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void cmbobat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat1ActionPerformed
        // TODO add your handling code here:
        
         try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat1.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
            
            hgobat1.setText(rs.getString(3));
            
            }
     else{
        
     }
} catch (Exception e){
        JOptionPane.showMessageDialog(null, "Tak ada");
}
                
        
    }//GEN-LAST:event_cmbobat1ActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:
        int hg1 = Integer.parseInt(hgobat1.getText());
         int tot1 = Integer.parseInt(total1.getText());
        
        int total = hg1 * tot1;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
        
        
    }//GEN-LAST:event_total1ActionPerformed

    private void total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total2ActionPerformed
        // TODO add your handling code here:
        int hg1 = Integer.parseInt(hgobat2.getText());
         int tot1 = Integer.parseInt(total2.getText());
         int tott = Integer.parseInt(txttotal.getText());
         
        int total =   hg1 * tot1 + tott  ;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
    }//GEN-LAST:event_total2ActionPerformed

    private void cmbobat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat2ActionPerformed
        // TODO add your handling code here:
         try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat2.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
            
            hgobat2.setText(rs.getString(3));
            
            }
     else{
         
     }
} catch (Exception e){
        JOptionPane.showMessageDialog(null, "Tak ada");
}
    }//GEN-LAST:event_cmbobat2ActionPerformed

    private void cmbobat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat3ActionPerformed
        // TODO add your handling code here:
         try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat3.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
           
            hgobat3.setText(rs.getString(3));
            
            }
     else{
         
     }
} catch (Exception e){
        JOptionPane.showMessageDialog(null, "Tak ada");
}
        
    }//GEN-LAST:event_cmbobat3ActionPerformed

    private void total3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total3ActionPerformed
        // TODO add your handling code here:
        int hg1 = Integer.parseInt(hgobat3.getText());
         int tot1 = Integer.parseInt(total3.getText());
         int tott = Integer.parseInt(txttotal.getText());
         
        int total = hg1 * tot1 + tott;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
    }//GEN-LAST:event_total3ActionPerformed

    private void cmbobat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat4ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat4.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
           
            hgobat4.setText(rs.getString(3));
            
            }
     else{
         
     }
} catch (Exception e){
        JOptionPane.showMessageDialog(null, "Tak ada");
}
    }//GEN-LAST:event_cmbobat4ActionPerformed

    private void total4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total4ActionPerformed
        // TODO add your handling code here:
        int hg1 = Integer.parseInt(hgobat4.getText());
         int tot1 = Integer.parseInt(total4.getText());
         int tott = Integer.parseInt(txttotal.getText());
         
        int total = hg1 * tot1 + tott;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
    }//GEN-LAST:event_total4ActionPerformed

    private void cmbobat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat5ActionPerformed
        // TODO add your handling code here:
            try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat5.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
           
            hgobat5.setText(rs.getString(3));
            
            }
     else{
         
     }
} catch (Exception e){
        JOptionPane.showMessageDialog(null, "Tak ada");
}
    }//GEN-LAST:event_cmbobat5ActionPerformed

    private void total5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total5ActionPerformed
        // TODO add your handling code here:
         int hg1 = Integer.parseInt(hgobat5.getText());
         int tot1 = Integer.parseInt(total5.getText());
         int tott = Integer.parseInt(txttotal.getText());
         
        int total = hg1 * tot1 + tott;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
    }//GEN-LAST:event_total5ActionPerformed

    private void cmbobat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat6ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat6.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
           
            hgobat6.setText(rs.getString(3));
            
            }
     else{
        
     }
} catch (Exception e){
}

    }//GEN-LAST:event_cmbobat6ActionPerformed

    private void total6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total6ActionPerformed
        // TODO add your handling code here:
        int hg1 = Integer.parseInt(hgobat6.getText());
         int tot1 = Integer.parseInt(total6.getText());
         int tott = Integer.parseInt(txttotal.getText());
         
        int total = hg1 * tot1 + tott;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
    }//GEN-LAST:event_total6ActionPerformed

    private void cmbobat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobat7ActionPerformed
        // TODO add your handling code here:
          try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from obat where nm_obat='"+cmbobat7.getSelectedItem()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
           
            hgobat7.setText(rs.getString(3));
            
            }
     else{
         
     }
} catch (Exception e){
        
}
    }//GEN-LAST:event_cmbobat7ActionPerformed

    private void total7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total7ActionPerformed
        // TODO add your handling code here:
         int hg1 = Integer.parseInt(hgobat7.getText());
         int tot1 = Integer.parseInt(total7.getText());
         int tott = Integer.parseInt(txttotal.getText());
         
        int total = hg1 * tot1 + tott;
        String total1= Integer.toString(total);
        txttotal.setText(total1);
    }//GEN-LAST:event_total7ActionPerformed

    private void txtnorekamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnorekamActionPerformed
        // TODO add your handling code here:
        tampiluser();
    }//GEN-LAST:event_txtnorekamActionPerformed

    private void txtiddokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddokActionPerformed
        // TODO add your handling code here:
          try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from dokter where id_dokter='"+txtiddok.getText()+"'";
            ResultSet rs = s.executeQuery(sql);
     if (rs.next()){
           
            txtnamadok.setText(rs.getString(2));
            txtspesial.setText(rs.getString(4));
            txttampil.setText(rs.getString(6));
            
            
            ImageIcon gambar1 = new ImageIcon(txttampil.getText()); // jangan lupa import class ImageIcon
        tampil_gambar.setIcon(gambar1);
            
            
            }
     
     else{
         JOptionPane.showMessageDialog(null, "Tak ada");
     }
} catch (Exception e){
        
}
    }//GEN-LAST:event_txtiddokActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        new Home(Login1.kondisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laborat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laborat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laborat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laborat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             @Override
            public void run() {
                new laborat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JComboBox cmbobat1;
    private javax.swing.JComboBox cmbobat2;
    private javax.swing.JComboBox cmbobat3;
    private javax.swing.JComboBox cmbobat4;
    private javax.swing.JComboBox cmbobat5;
    private javax.swing.JComboBox cmbobat6;
    private javax.swing.JComboBox cmbobat7;
    private javax.swing.JLabel hgobat1;
    private javax.swing.JLabel hgobat2;
    private javax.swing.JLabel hgobat3;
    private javax.swing.JLabel hgobat4;
    private javax.swing.JLabel hgobat5;
    private javax.swing.JLabel hgobat6;
    private javax.swing.JLabel hgobat7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ldate;
    private javax.swing.JLabel tampil_gambar;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField total3;
    private javax.swing.JTextField total4;
    private javax.swing.JTextField total5;
    private javax.swing.JTextField total6;
    private javax.swing.JTextField total7;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtiddok;
    private javax.swing.JTextField txtjamin;
    private javax.swing.JComboBox txtjenis;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamadok;
    private javax.swing.JTextField txtnorekam;
    private javax.swing.JTextField txtspesial;
    private javax.swing.JLabel txttampil;
    private javax.swing.JLabel txttotal;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
}
