/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angcmd
 */
public class obat extends javax.swing.JFrame {

    /**
     * Creates new form obat
     */
    private DefaultTableModel model;
    Date today = new Date();
    koneksi koneksi;
    public obat() {
        initComponents();
        autokode();            
        setTitle("Riez Hadiningrat");
        ldate.setText(today.toString());
        model=new DefaultTableModel();
        tblobat.setModel(model);
        model.addColumn("Kode");
        model.addColumn("Nama Obat");
        model.addColumn("Harga");
        model.addColumn("Stok");
        loadData();
    
    }
    private void search(String sql){
            
        model = new DefaultTableModel();
        tblobat.setModel(model);
         model.addColumn("Kode");
        model.addColumn("Nama Obat");
        model.addColumn("Harga");
        model.addColumn("Stok");
        
        String cari = txtcari.getText();
            try {
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
          
            ResultSet rs = s.executeQuery(sql);
        if (rs.next()){
            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
        }
        else {
            JOptionPane.showMessageDialog(this,"DATA TIDAK ADA","ALERT",JOptionPane.ERROR_MESSAGE);
            
        }
         tblobat.setModel(model);
        }catch(SQLException e){
        
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblobat = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ldate = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        cmdcari = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kode Obat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 122, -1, -1));

        jLabel3.setText("Nama Obat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setText("Stok");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtkd.setEnabled(false);
        getContentPane().add(txtkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 119, 198, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 198, -1));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 86, -1));
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 86, -1));

        tblobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblobatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblobat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 157, 530, 330));

        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        btnkeluar.setText("KEMBALI");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Daftar Obat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        ldate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(ldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 203, 27));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 230, 30));

        cmdcari.setText("CARI");
        cmdcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcariActionPerformed(evt);
            }
        });
        getContentPane().add(cmdcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autokode(){
    try{ Connection c=koneksi.getkoneksi();
     Statement s=c.createStatement();
     String sql= "SELECT MAX(right(kd_obat,4)) AS kd_obat FROM obat";
     ResultSet rs = s.executeQuery(sql);
        while(rs.next()){
                if(rs.first() == false){
                txtkd.setText("00001");
        }
                else {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<4-noLong;a++){
                        no = "0" + no;
         }
                   txtkd.setText(1+no);
               }       
            }
       rs.close();
       s.close(); }   
catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR: \n" + e.toString(),
                            "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
                String kd_obat=txtkd.getText();
        String nm_obat=txtnama.getText();
        String harga=txtharga.getText();
        String stok=txtstok.getText();
        try{
            Connection c=koneksi.getkoneksi();
            String sql="Insert into obat values(?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd_obat);
            p.setString(2, nm_obat);
            p.setString(3, harga);
            p.setString(4, stok);
            p.executeUpdate();
            p.close();
        }catch(SQLException e){
            System.out.println("Tidak bisa Isi");
            
        }finally{}loadData();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
         String kd=txtkd.getText();
        String nm=txtnama.getText();
        String hg=txtharga.getText();
        String st=txtstok.getText();
        try{
            Connection c=koneksi.getkoneksi();
            String sql="UPDATE `riez_husada`.`obat` SET `nm_obat` = ?, `harga` = ?, `stok` = ? WHERE `obat`.`kd_obat` = ?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, nm);
            p.setString(2, hg);
            p.setString(3, st);
            p.setString(4, kd);
            p.executeUpdate();
            p.close();
        }catch(SQLException e){
            System.out.println("Tidak bisa Isi");
            
        }finally{}loadData();
                        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
         int i=tblobat.getSelectedRow();
        if(i==-1)
        {
            return;
        }
        String id=(String) model.getValueAt(i, 0);
        
        
        try{
            Connection c=koneksi.getkoneksi();
            String sql="DELETE from obat WHERE kd_obat=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
            
        }catch(SQLException e){
            System.out.println("gagal delete");
            
        }finally{loadData();
        }
            
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtkd.setText(null);
        txtnama.setText(null);
        txtharga.setText(null);
        txtstok.setText(null);
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        new Home(Login1.kondisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tblobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblobatMouseClicked
        // TODO add your handling code here:
         int i=tblobat.getSelectedRow();
        if(i==-1)
        {
            return;
        }
        String no=(String) model.getValueAt(i, 0);
        txtkd.setText(no);
        String nama=(String) model.getValueAt(i, 1);
        txtnama.setText(nama);
        String harga=(String) model.getValueAt(i, 2);
        txtharga.setText(harga);
        String stok=(String) model.getValueAt(i, 3);
        txtstok.setText(stok);
    }//GEN-LAST:event_tblobatMouseClicked

    private void cmdcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcariActionPerformed
        // TODO add your handling code here:
        String cari = txtcari.getText();
        String sql= "select * from obat where nm_obat like'"+cari+"%'";

        search(sql);
        txtcari.setText(null);

    }//GEN-LAST:event_cmdcariActionPerformed

   public void loadData(){
      // txtkd.setText(null);
       txtnama.setText(null);
       txtharga.setText(null);
       txtstok.setText(null);
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    try{
        Connection c = koneksi.getkoneksi();
        Statement s = c.createStatement();
        String sql="Select * from obat";
        ResultSet r=s.executeQuery(sql);
        while(r.next()){
            Object[] o=new Object[4];
            o[0]=r.getString("kd_obat");
            o[1]=r.getString("nm_obat");
            o[2]=r.getString("harga");
            o[3]=r.getString("stok");
            model.addRow(o);
            
        }
        r.close();
        s.close();
        
    }catch(SQLException e){
        System.out.println("tdk bisa Load");
        
    }
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton cmdcari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel ldate;
    private javax.swing.JTable tblobat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
