/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ultramen
 */
public class Penggajian extends javax.swing.JFrame {

    /**
     * Creates new form Penggajian
     */
    private  DefaultTableModel model;
    public Penggajian() {
        initComponents();
        gambar.setVisible(false);
         model = new DefaultTableModel();
        tblgaji.setModel(model);
        model.addColumn("id");
        model.addColumn("nama");
        model.addColumn("jenis_kelamin");
        model.addColumn("profesi");
        model.addColumn("gaji");
        model.addColumn("masuk");
        model.addColumn("lembur");
        model.addColumn("izin");
        model.addColumn("tidak");
        model.addColumn("total");
        loadData();
    }
    public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = koneksi.getkoneksi();
            try (Statement s = c.createStatement()) {
                String sql = "Select * from gaji";
            try (ResultSet r = s.executeQuery(sql)) {
                    while (r.next()) {
                        Object[] o = new Object[10];
                        o[0] = r.getString("id_karyawan");
                        o[1] = r.getString("nama");
                        o[2] = r.getString("jenis_kelamin");
                        o[3] = r.getString("profesi");
                        o[4] = r.getString("gaji");
                        o[5] = r.getString("masuk");
                        o[6] = r.getString("lembur");
                        o[7] = r.getString("izin");
                        o[8] = r.getString("tidak");
                        o[9] = r.getString("total");
                        model.addRow(o);
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println("tdk Bisa Load");
        }
    }
     private void clear() {
        txtid.setText("");
        txtnama.setText("");
        txtjenis.setText("");
        txtprofesi.setText("");
        txtgaji.setText("");
        txtmasuk.setText("");
        txtlembur.setText("");
        txtizin.setText("");
        txttidak.setText("");
        txttotal.setText("");
     }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttidak = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtprofesi = new javax.swing.JTextField();
        txtmasuk = new javax.swing.JTextField();
        txtlembur = new javax.swing.JTextField();
        txtizin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgaji = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txttotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtgaji = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tampil_gambar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Penggajian Karyawan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("Id Karyawan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setText("Nama Karyawan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setText("Profesi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel7.setText("Masuk Kerja");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel8.setText("Lembur");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel9.setText("Izin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel10.setText("Tidak Masuk");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        txttidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttidakActionPerformed(evt);
            }
        });
        getContentPane().add(txttidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 40, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));

        txtnama.setEnabled(false);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, -1));

        txtjenis.setEnabled(false);
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 110, -1));

        txtprofesi.setEnabled(false);
        getContentPane().add(txtprofesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 110, -1));

        txtmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmasukActionPerformed(evt);
            }
        });
        getContentPane().add(txtmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 40, -1));

        txtlembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlemburActionPerformed(evt);
            }
        });
        getContentPane().add(txtlembur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 40, -1));

        txtizin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtizinActionPerformed(evt);
            }
        });
        getContentPane().add(txtizin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 40, -1));

        tblgaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblgaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgajiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblgaji);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 980, 240));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel11.setText("Total Gaji");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 180, -1));

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 90, -1));

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 90, -1));

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 90, -1));

        jButton4.setText("KEMBALI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 90, -1));

        txttotal.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 200, 50));

        jLabel12.setText("Gaji");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtgaji.setEnabled(false);
        getContentPane().add(txtgaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 110, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 2, 13)); // NOI18N
        jLabel13.setText("/ Hari");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 40, 20));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        jLabel14.setText("25000 / Jam");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 356, -1, 20));

        tampil_gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampil_gambar.setText("FOTO");
        tampil_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tampil_gambar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(tampil_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 310, 400));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Yakin Hapus BOK ??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
        int i=tblgaji.getSelectedRow();
        if(1==-1)
        {
            return;
        }

        String id=(String) model.getValueAt(i, 0);

        try {
            Connection c=koneksi.getkoneksi();
            String sql = "DELETE From gaji WHERE id_karyawan=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, id);

            p.executeUpdate();
            p.close();

        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());;
        }finally{
            loadData();
            clear();
            
            
        }
    } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
        try{
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
            String sql = "Select * from pendaftaran where id_karyawan='"+txtid.getText()+"'";
            ResultSet rs = s.executeQuery(sql);
            if (rs.next()){

                txtnama.setText(rs.getString(2));
                txtjenis.setText(rs.getString(4));
                txtprofesi.setText(rs.getString(6));
                txtgaji.setText(rs.getString(7));
                gambar.setText(rs.getString(8));
                ImageIcon gambar1 = new ImageIcon(gambar.getText()); // jangan lupa import class ImageIcon
                tampil_gambar.setIcon(gambar1);
                

            }
            else{
                JOptionPane.showMessageDialog(null, "Tak ada");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tak ada");
        }
    }//GEN-LAST:event_txtidActionPerformed

    private void txtmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmasukActionPerformed
        // TODO add your handling code here:
         int itung1 =Integer.parseInt(txtgaji.getText());
        int itung2 =Integer.parseInt(txtmasuk.getText());
        
        
        int hasilnya= itung1 * itung2;
       String hasilnya1=Integer.toString(hasilnya);
        txttotal.setText(hasilnya1);
    }//GEN-LAST:event_txtmasukActionPerformed

    private void txtlemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlemburActionPerformed
        // TODO add your handling code here:
        int itung1 =Integer.parseInt(txttotal.getText());
        int itung2 =Integer.parseInt(txtlembur.getText());
        
        
        int hasilnya= 25000 * itung2 + itung1;
       String hasilnya1=Integer.toString(hasilnya);
        txttotal.setText(hasilnya1);
    }//GEN-LAST:event_txtlemburActionPerformed

    private void txtizinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtizinActionPerformed
        // TODO add your handling code here:
         int itung1 =Integer.parseInt(txttotal.getText());
       int izin = Integer.parseInt(txtizin.getText());
        int itung =Integer.parseInt(txtgaji.getText());
        
        
        
        
        
        int hasilnya= itung1 - itung * izin  ;
       String hasilnya1=Integer.toString(hasilnya);
        txttotal.setText(hasilnya1);
    }//GEN-LAST:event_txtizinActionPerformed

    private void txttidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttidakActionPerformed
        // TODO add your handling code here:
        int itung1 =Integer.parseInt(txttotal.getText());
       int tidak = Integer.parseInt(txttidak.getText());
        int itung =Integer.parseInt(txtgaji.getText());
        
        
        
        
        
        int hasilnya= itung1 - itung * tidak ;
       String hasilnya1=Integer.toString(hasilnya);
        txttotal.setText(hasilnya1);
    }//GEN-LAST:event_txttidakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        String id = txtid.getText();
        String jenis = txtjenis.getText();
        String nama = txtnama.getText();
        String profesi = txtprofesi.getText();
        String gaji = txtgaji.getText();
        String masuk = txtmasuk.getText();
       String lembur = txtlembur.getText();
        
           String izin = txtizin.getText();
      String tidak = txttidak.getText();
      String total = txttotal.getText();
      
    
        
        int ok = JOptionPane.showConfirmDialog(null, "Yakin BOK ??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){

        
        try {
            Connection c = koneksi.getkoneksi();
            String sql = "Insert Into gaji Values (?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
            p.setString(1, id);
            p.setString(2, nama);
            p.setString(3, jenis);
            p.setString(4, profesi);
            p.setString(5, gaji);
            p.setString(6, masuk);
            p.setString(7, lembur);
            p.setString(8, izin);
            p.setString(9, tidak);
            
            p.setString(10, total);
            

            p.executeUpdate();
            p.close();

        } catch (SQLException e) {
            System.out.println("Tidak Bisa Isi");
        } finally {
            loadData();
            

            if (txtid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,"Periksa Kembali");
            } else {

                clear();
               tampil_gambar.setText(null);
               txtid.requestFocus();

            }

        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            if (txtnama.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Nama Tidak Boleh KOSONG BOK", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
               Connection c = koneksi.getkoneksi();
                Statement s=c.createStatement();
              
                String sql ="update gaji set nama='" + txtnama.getText() + "',jenis_kelamin='" + txtjenis.getText() + "',"
                        + "profesi='" + txtprofesi.getText()+ "',gaji='" + txtgaji.getText() + "',"
                        + "masuk='" + txtmasuk.getText()+ "',lembur='" + txtlembur.getText() + "',"
                        + "izin='"+txtizin.getText()+"',tidak='"+txttidak.getText()+"',"
                        + "total='"+txttotal.getText()+"' where id_karyawan='" + txtid.getText()+"'";
                 boolean r=s.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Update Tersimpan !", "Update", JOptionPane.INFORMATION_MESSAGE);
                clear();
                loadData();
                
                tampil_gambar.setText("");
            }
            loadData();
            
        }catch(SQLException error_update){
            JOptionPane.showMessageDialog(rootPane, "Error : "+error_update.getMessage(), "Update Gagal", JOptionPane.ERROR_MESSAGE);
            clear();
           
            tampil_gambar.setText(null);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblgajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgajiMouseClicked
        // TODO add your handling code here:
        int i = tblgaji.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id=(String) model.getValueAt(i, 0);
        txtid.setText(id);
        String nama = (String) model.getValueAt(i, 1);
        txtnama.setText(nama);
        String jenis = (String) model.getValueAt(i, 2);
        txtjenis.setText(jenis);
        String profesi = (String) model.getValueAt(i, 3);
        txtprofesi.setText(profesi);
        String gaji = (String) model.getValueAt(i, 4);
        txtgaji.setText(gaji);
        
        String masuk = (String) model.getValueAt(i, 5);
        txtmasuk.setText(masuk);
        String lembur = (String) model.getValueAt(i, 6);
        txtlembur.setText(lembur);
        String izin = (String) model.getValueAt(i, 7);
        txtizin.setText(izin);
        String tidak = (String) model.getValueAt(i, 8);
        txttidak.setText(izin);
        String total = (String) model.getValueAt(i, 9);
        txttotal.setText(total);

       

    }//GEN-LAST:event_tblgajiMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Home(Login1.kondisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penggajian().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tampil_gambar;
    private javax.swing.JTable tblgaji;
    private javax.swing.JTextField txtgaji;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtizin;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtlembur;
    private javax.swing.JTextField txtmasuk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtprofesi;
    private javax.swing.JTextField txttidak;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
