/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author root
 */
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 
import java.text.DateFormat; 
import java.text.SimpleDateFormat; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.util.HashMap;
import java.util.Map;
import javax.swing.Timer;

public class Rekamedis extends javax.swing.JFrame {

    /**
     * Creates new form Rekamedis
     */
    Date today = new Date();
    private  DefaultTableModel model;

    public Rekamedis() {
        initComponents();
        autokode();
        setTitle("Riez Hadiningrat");
        ldate.setText(today.toString());

    
        model = new DefaultTableModel();
        tblrekam.setModel(model);
        model.addColumn("no_rekamedis");
        model.addColumn("nama");
        model.addColumn("alamat");
        model.addColumn("jenis_kelamin");
        model.addColumn("umur");
        model.addColumn("jaminan");
        loadData();
    }
    

    private void clear() {
        norekam.setText("");
        txtnama.setText("");
        txtumur.setText("");
        txtalamat.setText("");
        txtjenis.setSelectedIndex(0);
        txtjaminan1.setSelectedIndex(0);

    }
 
    
   
    
   
    Statement statement;
    ResultSet resultSet;

    private void deleteData() {
        String sql_delete = "DELETE FROM rekamedis WHERE no_rekamedis = '" + norekam.getText() + "'";
        try {
            statement.executeUpdate(sql_delete);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
       
        private void search(String sql){
            
        model = new DefaultTableModel();
        tblrekam.setModel(model);
        model.addColumn("no_rekamedis");
        model.addColumn("nama");
        model.addColumn("alamat");
        model.addColumn("jenis_kelamin");
        model.addColumn("umur");
        model.addColumn("jaminan");
        
        String cari = txtcari.getText();
            try {
            Connection c=koneksi.getkoneksi();
            Statement s=c.createStatement();
          
            ResultSet rs = s.executeQuery(sql);
        if (rs.next()){
            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
        }
        else {
            JOptionPane.showMessageDialog(this,"DATA TIDAK ADA","ALERT",JOptionPane.ERROR_MESSAGE);
            
        }
         tblrekam.setModel(model);
        }catch(SQLException e){
        
        }
        }
            private void autokode(){
    try{ Connection c=koneksi.getkoneksi();
     Statement s=c.createStatement();
     String sql= "SELECT MAX(right(no_rekamedis,4)) AS no_rekamedis FROM rekamedis";
     ResultSet rs = s.executeQuery(sql);
        while(rs.next()){
                if(rs.first() == false){
                norekam.setText("0001");
        }
                else {
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                   //MENGATUR jumlah 0
                    for(int a=0;a<4-noLong;a++){
                        no = "0" + no;
         }
                   norekam.setText( 1+no);
               }       
            }
       rs.close();
       s.close(); }   
catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR: \n" + e.toString(),
                            "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        norekam = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtumur = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrekam = new javax.swing.JTable();
        txtjaminan1 = new javax.swing.JComboBox();
        txtjenis = new javax.swing.JComboBox();
        ldate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        cmdcari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Pendaftaran Pasien");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        norekam.setEnabled(false);
        norekam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norekamActionPerformed(evt);
            }
        });
        getContentPane().add(norekam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 152, 25));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 131, 245, 25));

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 162, 245, 67));

        txtumur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtumurActionPerformed(evt);
            }
        });
        getContentPane().add(txtumur, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 275, 41, 29));

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 385, -1, -1));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 385, -1, -1));

        tblrekam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblrekam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrekamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblrekam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 129, 521, 280));

        txtjaminan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "BPJS", "PBI", "NON-PBI", "UMUM" }));
        getContentPane().add(txtjaminan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 322, 139, 29));

        txtjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "laki-laki", "perempuan" }));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 240, 139, 29));

        ldate.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        getContentPane().add(ldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 10, 250, 27));

        jLabel3.setText("No Rekammedis");

        jLabel4.setText("Nama");

        jLabel5.setText("Alamat");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Umur");

        jLabel8.setText("Jaminan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 82, -1, -1));

        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 385, -1, -1));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 385, 90, -1));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 230, 30));

        cmdcari.setText("CARI");
        cmdcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcariActionPerformed(evt);
            }
        });
        getContentPane().add(cmdcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 80, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void norekamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norekamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_norekamActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtumurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtumurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtumurActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String jenis = txtjenis.getSelectedItem().toString();
        String jaminan = txtjaminan1.getSelectedItem().toString();
 int ok = JOptionPane.showConfirmDialog(null, "Yakin BOK??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
           
        String no_rekamedis = norekam.getText();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String umur = txtumur.getText();

        try {
            Connection d = koneksi.getkoneksi();
            String sql = "Insert Into rekamedis Values (?,?,?,?,?,?)";

            PreparedStatement p = (PreparedStatement) d.prepareStatement(sql);
            p.setString(1, no_rekamedis);
            p.setString(2, nama);
            p.setString(3, alamat);
            p.setString(4, jenis);
            p.setString(5, umur);
            p.setString(6, jaminan);
            p.executeUpdate();
            p.close();

           
        } catch (SQLException e) {
            System.out.println("Tidak Bisa Isi");
        } finally {
            loadData();

            if (norekam.getText().isEmpty()) ; if (txtnama.getText().isEmpty()); if (txtalamat.getText().isEmpty()) ; ; if (txtumur.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cek Maning BOK !");
                 
                 
            } else {

                clear();
                autokode();

            }
            
            
        }
            }


    }//GEN-LAST:event_simpanActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int ok = JOptionPane.showConfirmDialog(null, "Yakin Hapus BOK ??? ","",JOptionPane.YES_NO_OPTION);
        if (ok==0){
        int i=tblrekam.getSelectedRow();
if(1==-1)
{
	return;
}




try {
	Connection c=koneksi.getkoneksi();
	String sql = "DELETE From rekamedis WHERE no_rekamedis='"+norekam.getText()+"'";
	PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
	

	p.executeUpdate();
	p.close();

}catch(SQLException e) {
	JOptionPane.showMessageDialog(null, e.getMessage());;
}finally{
	loadData();
        clear();
        autokode();
}
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void tblrekamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrekamMouseClicked
        // TODO add your handling code here:
        int i = tblrekam.getSelectedRow();
        if (i == -1) {
            return;
        }
        String no_rekamedis = (String) model.getValueAt(i, 0);
        norekam.setText(no_rekamedis);
        String nama = (String) model.getValueAt(i, 1);
        txtnama.setText(nama);
        String alamat = (String) model.getValueAt(i, 2);
        txtalamat.setText(alamat);
        String jenis = (String) model.getValueAt(i, 3);
        txtjenis.setSelectedItem(jenis);
        String umur = (String) model.getValueAt(i, 4);
        txtumur.setText(umur);
        String jaminan = (String) model.getValueAt(i, 5);
        txtjaminan1.setSelectedItem(jaminan);
        
        
        
    }//GEN-LAST:event_tblrekamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home(Login1.kondisiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
        try{
            if (norekam.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Nomor Tidak Boleh KOSONG BOK", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
               Connection c = koneksi.getkoneksi();
                Statement s=c.createStatement();
              
                String sql ="update rekamedis set nama='" + txtnama.getText() + "',alamat='" + txtalamat.getText()+"',jenis_kelamin='" + txtjenis.getSelectedItem() + "',umur='" + txtumur.getText()+"',jaminan='" + txtjaminan1.getSelectedItem() + "' where no_rekamedis='" + norekam.getText() + "'";
                 boolean r=s.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Update Tersimpan !", "Update", JOptionPane.INFORMATION_MESSAGE);
            }
            loadData();
        }catch(SQLException error_update){
            JOptionPane.showMessageDialog(rootPane, "Error : "+error_update.getMessage(), "Update Gagal", JOptionPane.ERROR_MESSAGE);
            clear();
            autokode();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcariActionPerformed
        // TODO add your handling code here:
        String cari = txtcari.getText();
        String sql= "select nama from rekamedis where nama like'"+cari+"%'";
        
        search(sql);
        txtcari.setText(null);
      
    }//GEN-LAST:event_cmdcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rekamedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rekamedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rekamedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rekamedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rekamedis().setVisible(true);
            }
        });
    }

    public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = koneksi.getkoneksi();
            try (Statement s = c.createStatement()) {
                String sql = "Select * from rekamedis";
                try (ResultSet r = s.executeQuery(sql)) {
                    while (r.next()) {
                        Object[] o = new Object[6];
                        o[0] = r.getString("no_rekamedis");
                        o[1] = r.getString("nama");
                        o[2] = r.getString("alamat");
                        o[3] = r.getString("jenis_kelamin");
                        o[4] = r.getString("umur");
                        o[5] = r.getString("jaminan");
                        model.addRow(o);
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println("tdk Bisa Load");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cmdcari;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ldate;
    private javax.swing.JTextField norekam;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tblrekam;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JComboBox txtjaminan1;
    private javax.swing.JComboBox txtjenis;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
}
